---
# file: site.yml

- hosts: scrutiny_web
  become: true

  vars_files:
    - vars/settings.yml

  roles:
  #- buluma.influxdb2
  - zorlin.influxdb2
  - webapp

- hosts: scrutiny_collector
  become: true

  vars_files:
    - vars/settings.yml

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - geerlingguy.git
    - zorlin.smartmontools
    - collector

  tasks:
    - debug:
        msg:
          - "If you're reading this, Scrutiny has been successfully deployed."
          - "Let us know if it worked, and feel free to reach out if you need help. Enjoy!"
