---
# Name: Install and configure the collector's dependencies

- name: Software - Install dependencies (base)
  yum:
    name: crontabs
    state: present

- name: Software - Install dependencies (CentOS 8+)
  debug:
    msg: "CentOS 8+ not yet supported by the collector"
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 8

- name: Software - Install dependencies (CentOS 7)
  yum:
    name: smartmontools
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
