---
# Name: Install and configure the collector

# Dependencies
- name: Software - Install dependencies (base)
  apt:
    name: cron
    state: present

- name: Software - Install dependencies (for Ubuntu 20.04 / Debian 10 or above)
  apt:
    name: smartmontools
    state: present
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
      or ansible_distribution == 'Debian' and ansible_distribution_version|int >= 10

- name: Software - Install dependencies (for Ubuntu 18.04)
  apt:
    name: smartmontools
    state: present
    default_release: bionic-backports
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

# Directory structure
- name: Files - Create a directory to hold Scrutiny-related stuff
  file: path=/opt/scrutiny state=directory

- name: Files - Create a directory to store binaries
  file: path=/opt/scrutiny/bin state=directory

# Binary (autodetects architecture)
- name: Binary - Install the collector binary (amd64)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.1/scrutiny-collector-metrics-linux-amd64
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    checksum: sha256:72c2b4c8d1c796c32c29217e3ac6268a8d61755800121a59b9d45ecfe8bf5746
    mode: '0755'
  when: ansible_architecture == "x86_64"

- name: Binary - Install the collector binary (arm64)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.1/scrutiny-collector-metrics-linux-arm64
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    checksum: sha256:a9c06d05408d912aaf50072c54a4c445525e7e356b71c7acb32797450f5c12d1
    mode: '0755'
  when: ansible_architecture == "aarch64"

- name: Binary - Install the collector binary (arm32)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.1/scrutiny-collector-metrics-linux-arm
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    checksum: sha256:f9d2e0d036104458a499e905596b0bda633a99733fa6883a41102b285cc7107d
    mode: '0755'
  when: ansible_architecture == "armv7l"

# Cron
- name: Cron - Create a root crontab entry to run the collector periodically
  cron:
    name: "Scrutiny - Run the Collector"
    minute: "*/15"
    job: . /etc/profile; /opt/scrutiny/bin/scrutiny-collector-metrics-linux run --api-endpoint "http://{{ webapp_server }}:8080"
    user: root
