---
# Name: Install and configure the collector's dependencies

- name: Software - Install dependencies (base)
  apt:
    name: cron
    state: present

- name: Software - Install dependencies (for Ubuntu 20.04 / Debian 10 or above)
  apt:
    name: smartmontools
    state: present
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
      or ansible_distribution == 'Debian' and ansible_distribution_version|int >= 10

- name: Software - Install dependencies (for Ubuntu 18.04)
  apt:
    name: smartmontools
    state: present
    default_release: bionic-backports
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: Software- Enable backports repository (for Debian 9)
  apt_repository
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '9'
