---
# Name: Install and configure the collector

# Dependencies
# Ubuntu/Debian are the same for this role.
- include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

# Directory structure
- name: Files - Create a directory to hold Scrutiny-related stuff
  file: path=/opt/scrutiny state=directory

- name: Files - Create a directory to store binaries
  file: path=/opt/scrutiny/bin state=directory

# Binary (autodetects architecture)
- name: Binary - Install the collector binary (amd64)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.5/scrutiny-collector-metrics-linux-amd64
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    checksum: sha256:5e44b663f4f78dd830611321d5497360a6e881bb0bcd491bbde0919b33081c58
    mode: '0755'
  when: ansible_architecture == "x86_64"

- name: Binary - Install the collector binary (arm64)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.5/scrutiny-collector-metrics-linux-arm64
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    checksum: sha256:0f833a1b2ab43e489809e2bca69d9c739dd19c4b33ce115e675a485cd76b7900
    mode: '0755'
  when: ansible_architecture == "aarch64"

- name: Binary - Install the collector binary (arm32)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.5/scrutiny-collector-metrics-linux-arm-7
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    checksum: sha256:7981b6abdfbe96dae7617fa2ef6f53a63ee37a0093a9f3455e91ce2cf8dc1d77
    mode: '0755'
  when: ansible_architecture == "armv7l"

# Cron
- name: Cron - Create a root crontab entry to run the collector periodically
  cron:
    name: "Scrutiny - Run the Collector"
    minute: "*/15"
    job: . /etc/profile; /opt/scrutiny/bin/scrutiny-collector-metrics-linux run --api-endpoint "http://{{ webapp_server }}:8080"
    user: root
