---
# Name: Install and configure the collector

# Dependencies
# Ubuntu/Debian are the same for this role.
- include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

# Directory structure
- name: Files - Create a directory to hold Scrutiny-related stuff
  file: path=/opt/scrutiny state=directory

- name: Files - Create a directory to store binaries
  file: path=/opt/scrutiny/bin state=directory

# Binary (autodetects architecture)
- name: Binary - Install the collector binary (amd64)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/{{ scrutiny_version }}/scrutiny-collector-metrics-linux-amd64
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    mode: '0755'
  when: ansible_architecture == "x86_64"

- name: Binary - Install the collector binary (arm64)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/{{ scrutiny_version }}/scrutiny-collector-metrics-linux-arm64
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    mode: '0755'
  when: ansible_architecture == "aarch64"

- name: Binary - Install the collector binary (arm32)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/{{ scrutiny_version }}/scrutiny-collector-metrics-linux-arm-7
    dest: /opt/scrutiny/bin/scrutiny-collector-metrics-linux
    mode: '0755'
  when: ansible_architecture == "armv7l"

# Cron
# - name: Cron - Create a root crontab entry to run the collector periodically
#   cron:
#     name: "Scrutiny - Run the Collector"
#     minute: "*/15"
#     job: . /etc/profile; /opt/scrutiny/bin/scrutiny-collector-metrics-linux run --api-endpoint "http://{{ webapp_server }}:8080"
#     user: root
