---
# Name: Install and configure the collector

# Ubuntu/Debian are the same for this role.
- include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'
