---
# Name: Install and configure the webapp

# Dependencies
# Debian and Ubuntu are the same for this role.
- include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

# Directory structure
- name: Files - Create a directory to hold Scrutiny-related stuff
  file: path=/opt/scrutiny state=directory

- name: Files - Create a configuration directory
  file: path=/opt/scrutiny/config state=directory

- name: Files - Create a directory to store the webapp
  file: path=/opt/scrutiny/web state=directory

- name: Files - Create a directory to store binaries
  file: path=/opt/scrutiny/bin state=directory

# Configuration
- name: Configuration - configure scrutiny
  template: src=scrutiny.yaml.j2 dest=/opt/scrutiny/config/scrutiny.yaml mode=0644

# Binary (autodetects architecture)
- name: Binary - Install the webapp binary (amd64)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.1/scrutiny-web-linux-amd64
    dest: /opt/scrutiny/bin/scrutiny-web-linux
    checksum: sha256:7d1942616692f2bbc3ecda13ba246040b37195b2c9330c3a50f01f73a6bc61a0
    mode: '0755'
  when: ansible_architecture == "x86_64"

- name: Binary - Install the webapp binary (arm64)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.1/scrutiny-web-linux-arm64
    dest: /opt/scrutiny/bin/scrutiny-web-linux
    checksum: sha256:b120c17b5a6a3500cb93088d91bf3ceae0134a2b1119f85c6cd12b32dd193600
    mode: '0755'
  when: ansible_architecture == "aarch64"

- name: Binary - Install the webapp binary (arm32)
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/0.3.1/scrutiny-web-linux-arm
    dest: /opt/scrutiny/bin/scrutiny-web-linux
    checksum: sha256:d060a8cb9c06515b09777cb61b7856285c6f50848803da9be0497031584010cf
    mode: '0755'
  when: ansible_architecture == "armv7l"

# Frontend
- name: Frontend - Download and install the frontend files
  unarchive:
    src: https://github.com/AnalogJ/scrutiny/releases/download/0.3.1/scrutiny-web-frontend.tar.gz
    dest: /opt/scrutiny/web
    remote_src: yes
    extra_opts: "--strip-components=1"
